"""Register module 2 models

Revision ID: 055b685c7938
Revises: 4ad519af44d9
Create Date: 2025-12-31 18:02:06.318670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055b685c7938'
down_revision: Union[str, Sequence[str], None] = '4ad519af44d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fabric_types', sa.Column('cost_per_yard', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('fabric_types', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fabric_types', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fabric_types', type_='foreignkey')
    op.drop_column('fabric_types', 'supplier_id')
    op.drop_column('fabric_types', 'cost_per_yard')
    # ### end Alembic commands ###
