"""Add cost and profit columns

Revision ID: 4ad519af44d9
Revises: e001149b4fe9
Create Date: 2025-12-30 18:13:43.217371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad519af44d9'
down_revision: Union[str, Sequence[str], None] = 'e001149b4fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fabric_types_id'), 'fabric_types', ['id'], unique=False)
    op.create_index(op.f('ix_fabric_types_name'), 'fabric_types', ['name'], unique=True)
    op.add_column('order_items', sa.Column('cost_per_unit', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('total_cost', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_cost', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('estimated_profit', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'estimated_profit')
    op.drop_column('orders', 'total_cost')
    op.drop_column('order_items', 'total_cost')
    op.drop_column('order_items', 'cost_per_unit')
    op.drop_index(op.f('ix_fabric_types_name'), table_name='fabric_types')
    op.drop_index(op.f('ix_fabric_types_id'), table_name='fabric_types')
    # ### end Alembic commands ###
