"""Add deposit and balance columns

Revision ID: 50feb40c64ef
Revises: 45fd5feb4703
Create Date: 2026-01-03 07:33:46.517323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50feb40c64ef'
down_revision: Union[str, Sequence[str], None] = '45fd5feb4703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('deposit', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'balance')
    op.drop_column('orders', 'deposit')
    # ### end Alembic commands ###
