"""add_audit_log_table

Revision ID: 93ba062baeb1
Revises: 50feb40c64ef
Create Date: 2026-01-05 08:51:22.577797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ba062baeb1'
down_revision: Union[str, Sequence[str], None] = '50feb40c64ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_tiers_id'), table_name='price_tiers')
    op.drop_table('price_tiers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_tiers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('min_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('price_tiers_pkey'))
    )
    op.create_index(op.f('ix_price_tiers_id'), 'price_tiers', ['id'], unique=False)
    # ### end Alembic commands ###
