"""Add average_weight_g to product_types

Revision ID: a939c4786680
Revises: 055b685c7938
Create Date: 2026-01-01 22:37:24.207065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a939c4786680'
down_revision: Union[str, Sequence[str], None] = '055b685c7938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_types', sa.Column('average_weight_g', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_types', 'average_weight_g')
    # ### end Alembic commands ###
